# Generated by Django 4.2.7 on 2023-11-17 19:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="profile_picture",
            field=models.ImageField(default=111, upload_to=""),
            preserve_default=False,
        ),
    ]
